services:
  postgres:
    image: postgres:17

    container_name: postgres-lab

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: devsecops_lab

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
