services:
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend

  nginx:
    image: nginx

    ports:
      - '8080:80'
      - '8443:443'

    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl

    depends_on:
      - frontend
      - backend
