server {
    listen 80;

    return 301 https://localhost:8443$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api {
        proxy_pass http://backend:4000;
    }
}