services:
  app:
    build: ./app

    container_name: monitoring-app

    ports:
      - '3000:3000'

    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - '9090:9090'

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
